apiVersion: v1
kind: Service
metadata:
  name: laravelvuejs-service
spec:
  selector:
    app: laravel-vuejs           
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
  type: LoadBalancer  
  
